theme: jekyll-theme-minimal

# This controls the sidebar Title and page-name
title: ðŸ’»ðŸ‘¨ðŸ»â€ðŸŽ“ðŸš´ðŸ¼â€â™‚ï¸ðŸš£ðŸ¼â€â™‚ï¸ðŸ¦¾

# This controls the left sidebar content 
description: > 
  Luke J Andrews - blog et al
  <br></br>
  Pages: <br>
  <a href="/"> CV </a><br>
  <a href="/thearchive"> The Archive </a>
  <br></br>
  Media: <br>
  <a href="https://www.linkedin.com/in/luke-andrews-758690154/"> Linked In </a>
  <br></br>
  Contact: <br>
  L.J.Andrews.UK@gmail.com <br>

show_downloads: "false"
logo: /assets/img/chain.png
